from backend.Model.DB.SQLServer import SQLSERVERDBModel
from backend.Controller.pathFinder import JSONFinder
from backend.Controller.analyser import SpeechRefinement

class SQLServerDataBaseController:
    @staticmethod
    def add_qa_processes(id_grabacion, nombre, scores):
        server = SQLSERVERDBModel()
        server.create_tables()

        telefono = nombre[4:-34]
        fecha = nombre[19:-14]

        jsonfinder = JSONFinder("../analysed_records/audio_text")

        audio = jsonfinder.find(nombre)

        refined_audio = SpeechRefinement.refine_speech_textOpenAI(audio['text'])

        server.add_grabaciones(id_grabacion, nombre, telefono, fecha, refined_audio)

        server.add_autogenerated_scores(id_grabacion, scores)
